### ISSUE TITLE
test, build and src jQuery subfolders causing build errors.

### ISSUE THREAD

**Issue by maxmechanic** [broccolijs/broccoli-sample-app#7]
With broccoli-cli installed, cloning the broccoli-sample-app repo and running `broccoli serve` after `npm install` and `bower install` throws errors and will not serve the app:
```
 In appkit/bower_components/jquery/build/release-notes.js:

Line 1: Unexpected token ILLEGAL

Error: Line 1: Unexpected token ILLEGAL
    at throwError (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2584:21)
    at scanPunctuator (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:1354:9)
    at advance (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2002:16)
    at peek (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:2028:21)
    at parseProgram (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5176:9)
    at broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:5661:38
    at parse (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:6038:23)
    at $Parser.parse (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:6810:17)
    at new $Parser.constructor (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:6803:12)
    at $Compiler.parse (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:6588:20)
    at new $Compiler.constructor (broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:6585:12)
    at addModule (broccoli-sample-app/node_modules/broccoli-es6-concatenator/index.js:80:24)
    at ES6Concatenator.transform (broccoli-sample-app/node_modules/broccoli-es6-concatenator/index.js:53:5)
    at broccoli-sample-app/node_modules/broccoli-es6-concatenator/node_modules/broccoli-transform/index.js:13:19
    at invokeCallback (broccoli-sample-app/node_modules/broccoli/node_modules/rsvp/dist/commonjs/rsvp/promise.js:228:21)
    at publish (broccoli-sample-app/node_modules/broccoli/node_modules/rsvp/dist/commonjs/rsvp/promise.js:176:9)
    at publishFulfillment (broccoli-sample-app/node_modules/broccoli/node_modules/rsvp/dist/commonjs/rsvp/promise.js:312:5)
    at flush (broccoli-sample-app/node_modules/broccoli/node_modules/rsvp/dist/commonjs/rsvp/asap.js:41:9)
    at process._tickDomainCallback (node.js:459:13)
```
 It seems to be trying to include those files in addition to the built version of jQuery when doing es6 concatenation/compilation; deleting those folders lets the app build and run as expected. 

What is the idiomatic way with Broccoli to exclude these files? Am I missing something else about configuration?

I'm running Node 0.10.26 and Bower 1.2.8 on OS X.

**Comment by maxmechanic** [comment]
Closed by #8.
